version: '{branch}-{build}'

skip_commits:
  files:
    - README.md
    - doc/**/*

os:
  - Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

environment:
  matrix:
    - GENERATOR: Visual Studio 15 2017

    - GENERATOR: Visual Studio 15 2017 Win64

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: Visual Studio 16 2019

init: []

before_build:
- if defined BINDIR (set "PATH=%BINDIR%;%PATH:C:\Program Files\Git\usr\bin;=%")
- md build
- cd build
- cmake -Wno-dev --config "%CONFIGURATION%" -G "%GENERATOR%" ..

build_script:
- cmake --build . --config "%CONFIGURATION%"

test_script:
- ctest -C "%CONFIGURATION%" --output-on-failure
